'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3643
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MyRaceGame.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!doctype html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;meta charset=&quot;utf-8&quot;&gt;
        '''&lt;title&gt;Bankrupt| Chicken Racer Help&lt;/title&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body&gt;
        '''&lt;h1&gt;Bankrupt&lt;/h1&gt;
        '''&lt;/body&gt;
        '''&lt;/html&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property bankrupt() As String
            Get
                Return ResourceManager.GetString("bankrupt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!doctype html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;meta charset=&quot;utf-8&quot;&gt;
        '''&lt;title&gt;Betting | Chicken Racer Help&lt;/title&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body&gt;
        '''&lt;h1&gt;Betting&lt;/h1&gt;
        '''&lt;/body&gt;
        '''&lt;/html&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property betting() As String
            Get
                Return ResourceManager.GetString("betting", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property BlueChicken128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlueChicken128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!doctype html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;meta charset=&quot;utf-8&quot;&gt;
        '''&lt;title&gt;Double Money| Chicken Racer Help&lt;/title&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body&gt;
        '''&lt;h1&gt;Double Money&lt;/h1&gt;
        '''&lt;/body&gt;
        '''&lt;/html&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property double_money() As String
            Get
                Return ResourceManager.GetString("double_money", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!doctype html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;meta charset=&quot;utf-8&quot;&gt;
        '''&lt;title&gt;FAQ | Chicken Racer Help&lt;/title&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body&gt;
        '''&lt;h1&gt;Frequently Asked Questions&lt;/h1&gt;
        '''&lt;/body&gt;
        '''&lt;/html&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property faq() As String
            Get
                Return ResourceManager.GetString("faq", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property favicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property favicon1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property favicon2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property frmGame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frmGame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property g1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property g11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GreenChicken128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GreenChicken128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''     &lt;link rel=&quot;icon&quot; type=&quot;image/png&quot; href=&quot;/favicon.png&quot; /&gt;
        '''    &lt;link rel=&quot;shortcut icon&quot; type=&quot;image/x-icon&quot; href=&quot;icons/favicon.ico&quot;/&gt;
        '''    &lt;link href=&quot;help/helpstyle.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        '''    &lt;style&gt;body {
        '''    background-color: rgb(0, 0, 0);
        '''}
        '''h1 {
        '''    color: rgb(255, 255, 255);
        '''    margin-right: 30px;
        '''    margin-bottom: 30px;
        '''    border-color: red;
        '''}
        '''a {
        '''    color: blue;
        '''}
        '''#linkGoogle {
        '''    color: rgb(143, 5, 154);
        '''    font-style: ita [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help() As String
            Get
                Return ResourceManager.GetString("help", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property helpQuestion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("helpQuestion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to body {
        '''    background-color: rgb(0, 0, 0);
        '''}
        '''h1 {
        '''    color: rgb(255, 255, 255);
        '''    margin-right: 30px;
        '''    margin-bottom: 30px;
        '''    border-color: red;
        '''}
        '''a {
        '''    color: blue;
        '''}
        '''#linkGoogle {
        '''    color: rgb(143, 5, 154);
        '''    font-style: italic;
        '''}
        '''#linkCorey {
        '''    color: red;
        '''}
        '''h1 {
        '''    cursor: crosshair;
        '''}
        '''#pMain {
        '''    border-right: 500px none aqua;
        '''    border-top: 500px none aqua;
        '''    border-bottom: 500px none aqua;
        '''    color: orange;
        '''    text-shadow: rgb(53, 53, 94);
        '''    text-s [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property helpstyle() As String
            Get
                Return ResourceManager.GetString("helpstyle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!doctype html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;meta charset=&quot;utf-8&quot;&gt;
        '''&lt;title&gt;Home | Chicken Racer Help&lt;/title&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body&gt;
        '''
        '''&lt;h1&gt;Chicken Racer Help&lt;/h1&gt;
        '''&lt;p&gt;Having trouble with Chicken Racer? Don&apos;t worry. We have all the help you need here.&lt;/p&gt;
        '''&lt;p&gt;Just Select a Tab to view a different help topic.&lt;/p&gt;
        '''&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        '''
        '''&lt;/body&gt;
        '''&lt;/html&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property home() As String
            Get
                Return ResourceManager.GetString("home", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!doctype html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;meta charset=&quot;utf-8&quot;&gt;
        '''&lt;title&gt;How to Play | Chicken Racer Help&lt;/title&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body&gt;
        '''&lt;h1&gt;How to Play&lt;/h1&gt;
        '''  &lt;p&gt;To begin playing...&lt;/p&gt;
        '''  &lt;hr&gt;&lt;/hr&gt;
        '''  &lt;p&gt;First Click a player name so that you can enter your own name.&lt;/p&gt;
        '''  &lt;p&gt;After entering you own name. Type a bet into the betting boc for your player.&lt;/p&gt;
        '''  &lt;p&gt;After you have entered a bet, you can click the Double Money button if you would like to try earn double money.&lt;/p&gt;
        '''  &lt;p&gt;If you do try for double money the [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property howtoplay() As String
            Get
                Return ResourceManager.GetString("howtoplay", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property leaderboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leaderboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!doctype html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;meta charset=&quot;utf-8&quot;&gt;
        '''&lt;title&gt;Leaderboards | Chicken Racer Help&lt;/title&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body&gt;
        '''&lt;h1&gt;Leaderboards&lt;/h1&gt;
        '''&lt;/body&gt;
        '''&lt;/html&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property leaderboards() As String
            Get
                Return ResourceManager.GetString("leaderboards", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!doctype html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;meta charset=&quot;utf-8&quot;&gt;
        '''&lt;title&gt;Game Overview| Chicken Racer Help&lt;/title&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body&gt;
        '''&lt;h1&gt;Overview of Chicken Racer&lt;/h1&gt;
        '''    &lt;img src=&quot;../frmGame.jpg&quot; alt=&quot;An Overview of the Game&quot; width=&quot;600&quot; height=&quot;600&quot; /&gt;
        '''&lt;/body&gt;
        '''&lt;/html&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property overview() As String
            Get
                Return ResourceManager.GetString("overview", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property overviewpdf() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("overviewpdf", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property overviewpdf1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("overviewpdf1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!doctype html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;meta charset=&quot;utf-8&quot;&gt;
        '''&lt;title&gt;Pausing | Chicken Racer Help&lt;/title&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body&gt;
        '''&lt;h1&gt;Pausing the Game&lt;/h1&gt;
        '''&lt;/body&gt;
        '''&lt;/html&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property pausing() As String
            Get
                Return ResourceManager.GetString("pausing", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!doctype html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;meta charset=&quot;utf-8&quot;&gt;
        '''&lt;title&gt;Player Names| Chicken Racer Help&lt;/title&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body&gt;
        '''&lt;h1&gt;Changing Player Names&lt;/h1&gt;
        '''&lt;/body&gt;
        '''&lt;/html&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property playernames() As String
            Get
                Return ResourceManager.GetString("playernames", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property redblackyellow() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("redblackyellow", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property RedChicken128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedChicken128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property YellowChicken128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YellowChicken128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
